# Generated by Django 4.2.1 on 2023-10-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ainaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='')),
                ('video_url', models.FileField(blank=True, null=True, upload_to='')),
                ('content', models.TextField(blank=True, null=True)),
                ('fb_page_id', models.CharField(blank=True, max_length=30, null=True)),
                ('fb_page_access_token', models.CharField(blank=True, max_length=500, null=True)),
                ('fb_group_id', models.CharField(blank=True, max_length=30, null=True)),
                ('fb_user_access_token', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessConnect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='')),
                ('video_url', models.FileField(blank=True, null=True, upload_to='')),
                ('content', models.TextField(blank=True, null=True)),
                ('fb_page_id', models.CharField(blank=True, max_length=30, null=True)),
                ('fb_page_access_token', models.CharField(blank=True, max_length=500, null=True)),
                ('fb_group_id', models.CharField(blank=True, max_length=30, null=True)),
                ('fb_user_access_token', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConnectifyIndia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='')),
                ('video_url', models.FileField(blank=True, null=True, upload_to='')),
                ('content', models.TextField(blank=True, null=True)),
                ('fb_page_id', models.CharField(blank=True, max_length=30, null=True)),
                ('fb_page_access_token', models.CharField(blank=True, max_length=500, null=True)),
                ('fb_group_id', models.CharField(blank=True, max_length=30, null=True)),
                ('fb_user_access_token', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegalAspire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='')),
                ('video_url', models.FileField(blank=True, null=True, upload_to='')),
                ('content', models.TextField(blank=True, null=True)),
                ('fb_page_id', models.CharField(blank=True, max_length=30, null=True)),
                ('fb_page_access_token', models.CharField(blank=True, max_length=500, null=True)),
                ('fb_group_id', models.CharField(blank=True, max_length=30, null=True)),
                ('fb_user_access_token', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SimplyCounsel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='')),
                ('video_url', models.FileField(blank=True, null=True, upload_to='')),
                ('content', models.TextField(blank=True, null=True)),
                ('fb_page_id', models.CharField(blank=True, max_length=30, null=True)),
                ('fb_page_access_token', models.CharField(blank=True, max_length=500, null=True)),
                ('fb_group_id', models.CharField(blank=True, max_length=30, null=True)),
                ('fb_user_access_token', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
