# Generated by Django 4.2.1 on 2023-10-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMediaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ainaw',
            name='link_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessconnect',
            name='link_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectifyindia',
            name='link_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legalaspire',
            name='link_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simplycounsel',
            name='link_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
