# Generated by Django 4.2.1 on 2023-10-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMediaApp', '0003_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagram',
            name='fb_group_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='instagram',
            name='fb_page_access_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='instagram',
            name='fb_page_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='instagram',
            name='fb_user_access_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
