# Generated by Django 4.2.1 on 2023-10-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMediaApp', '0005_instagram_instagram_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagram',
            name='instagram_user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
