# Generated by Django 4.2.1 on 2023-10-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMediaApp', '0006_alter_instagram_instagram_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Twiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='')),
                ('video_url', models.FileField(blank=True, null=True, upload_to='')),
                ('content', models.TextField(blank=True, null=True)),
                ('link_url', models.URLField(blank=True, null=True)),
                ('bearer_token', models.CharField(blank=True, max_length=500, null=True)),
                ('consumer_key', models.CharField(blank=True, max_length=100, null=True)),
                ('consumer_secret', models.CharField(blank=True, max_length=200, null=True)),
                ('access_token', models.CharField(blank=True, max_length=500, null=True)),
                ('access_token_secret', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
