# Generated by Django 4.2.1 on 2023-11-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMediaApp', '0011_ainaw_document_businessconnect_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedln',
            name='thumbnail_url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
