# Generated by Django 4.2.1 on 2023-12-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMediaApp', '0012_linkedln_thumbnail_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_page_id', models.CharField(blank=True, max_length=30, null=True)),
                ('fb_page_access_token', models.CharField(blank=True, max_length=500, null=True)),
                ('fb_group_id', models.CharField(blank=True, max_length=30, null=True)),
                ('fb_user_access_token', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
