# Generated by Django 4.2.1 on 2023-12-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMediaApp', '0013_facebookmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookmodel',
            name='fb_group_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='facebookmodel',
            name='fb_page_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='facebookmodel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
