# Generated by Django 4.2.1 on 2024-01-07 10:57

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('password', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=254, unique=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(default='', max_length=254)),
                ('description', models.TextField(default=True)),
                ('content', tinymce.models.HTMLField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('carrier', 'carrier'), ('legal', 'legal'), ('ngo', 'ngo'), ('project', 'project')], max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bootcamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=254, unique=True)),
                ('title', models.CharField(max_length=254)),
                ('heading1', models.TextField(default=True, null=True)),
                ('heading2', models.TextField(default=True, null=True)),
                ('bootcamp_date_detail', models.TextField(default=True)),
                ('bootcamp_time_detail', models.CharField(max_length=254)),
                ('bootcamp_starting_date', models.CharField(max_length=254)),
                ('background_image_url', models.ImageField(default=True, upload_to='')),
                ('image_url1', models.ImageField(default=True, upload_to='')),
                ('image_url2', models.ImageField(default=True, upload_to='')),
                ('url', models.URLField(default=True)),
                ('name1', models.CharField(default=True, max_length=150)),
                ('name2', models.CharField(default=True, max_length=150)),
                ('desination1', models.CharField(default=True, max_length=254)),
                ('desination2', models.CharField(default=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='BootcampAcount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('country', models.CharField(default=True, max_length=254)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('category', models.CharField(max_length=254)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessDeveloper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('password', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Carreer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('region', models.CharField(default=True, max_length=254)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('password', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('slug', models.SlugField(max_length=254, unique=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(default=True)),
                ('content', tinymce.models.HTMLField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('simplycounsel', 'simplycounsel'), ('legalaspire', 'legalaspire'), ('ainaw', 'ainaw'), ('businessconnect', 'businessconnect')], max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=254, unique=True)),
                ('title', models.CharField(blank=True, max_length=254, null=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.CharField(blank=True, choices=[('career', 'career'), ('legal', 'legal'), ('ngo', 'ngo'), ('project', 'project')], max_length=100, null=True)),
                ('sub_category', models.CharField(blank=True, choices=[('word', 'word'), ('excell', 'excell'), ('powerpoint', 'powerpoint'), ('pdf', 'pdf')], max_length=100, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.TextField()),
                ('firstname', models.CharField(default=True, max_length=150)),
                ('lastname', models.CharField(default=True, max_length=150)),
                ('mobile', models.CharField(default=True, max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('location', models.CharField(default=True, max_length=100)),
                ('segment', models.TextField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormModel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.TextField()),
                ('firstname', models.CharField(default=True, max_length=150)),
                ('lastname', models.CharField(default=True, max_length=150)),
                ('mobile', models.CharField(default=True, max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('location', models.CharField(default=True, max_length=100)),
                ('segment', models.TextField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.TextField()),
                ('firstname', models.CharField(default=True, max_length=150)),
                ('lastname', models.CharField(default=True, max_length=150)),
                ('mobile', models.CharField(default=True, max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('location', models.CharField(default=True, max_length=100)),
                ('segment', models.TextField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormModel3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.TextField()),
                ('firstname', models.CharField(default=True, max_length=150)),
                ('lastname', models.CharField(default=True, max_length=150)),
                ('mobile', models.CharField(default=True, max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('location', models.CharField(default=True, max_length=100)),
                ('segment', models.TextField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormModel4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.TextField()),
                ('firstname', models.CharField(default=True, max_length=150)),
                ('lastname', models.CharField(default=True, max_length=150)),
                ('mobile', models.CharField(default=True, max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('location', models.CharField(default=True, max_length=100)),
                ('segment', models.TextField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormModel5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.TextField()),
                ('firstname', models.CharField(default=True, max_length=150)),
                ('lastname', models.CharField(default=True, max_length=150)),
                ('mobile', models.CharField(default=True, max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('location', models.CharField(default=True, max_length=100)),
                ('segment', models.TextField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormModel6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.TextField()),
                ('firstname', models.CharField(default=True, max_length=150)),
                ('lastname', models.CharField(default=True, max_length=150)),
                ('mobile', models.CharField(default=True, max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('location', models.CharField(default=True, max_length=100)),
                ('segment', models.TextField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormModel7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.TextField()),
                ('firstname', models.CharField(default=True, max_length=150)),
                ('lastname', models.CharField(default=True, max_length=150)),
                ('mobile', models.CharField(default=True, max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('location', models.CharField(default=True, max_length=100)),
                ('segment', models.TextField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('password', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('password', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=254, unique=True)),
                ('title', models.CharField(blank=True, max_length=254, null=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(default=True)),
                ('content', tinymce.models.HTMLField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=254, null=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('video', models.FileField(blank=True, default=True, null=True, upload_to='')),
            ],
        ),
    ]
